#!/usr/bin/env python3
import sys
import re

from subprocess import check_output

commit_msg_path = sys.argv[1]

with open(commit_msg_path, 'r+') as file:
    msg = file.read()    
    if re.match('^CM\d+.*:.+', msg):
        sys.exit(0)

    try:
        branch_name = check_output('git rev-parse --abbrev-ref HEAD'.split()).strip().decode()
        commit_count = int(check_output('git rev-list --count HEAD'.split()).strip().decode()) + 1
    
        file.seek(0, 0)
        file.write('CM{:04d} ({}): {}'.format(commit_count, branch_name, msg))
    except Exception:
        pass





